#!/bin/bash
$HOME/Downloads/Xyce-6.11.1/configure \
ARCHDIR=$HOME/XyceLibs/Serial12.12.1 \
CPPFLAGS="-I/usr/include/suitesparse -I/usr/local/include" \
CXXFLAGS="-O3" \
ADMS_CXXFLAGS="-O0" \
LDFLAGS="-L/usr/local/lib" \
CFLAGS="-O3" \
--disable-adms_sensitivities
